# Generated by Django 4.1.6 on 2023-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lun',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='storagepool',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vmdk',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
    ]
