# Generated by Django 4.1.6 on 2023-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage', '0002_alter_lun_size_alter_storagepool_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lun',
            name='wwn',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
